CREATE TABLE BOOKING(
	CUSTOMERID INT REFERENCES USERS(ID), 
	BOOKINGID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 50000, INCREMENT BY 1),
	RECNAME VARCHAR(30), 
	RECADDRESS VARCHAR(200), 
	RECPIN VARCHAR(10), 
	RECMOBILE VARCHAR(15), 
	PARWEIGHT DECIMAL(10, 2), 
	CONTENTDESCRIPTION VARCHAR(200), 
	DELIVERYTYPE VARCHAR(30), 
	PACKINGPREF VARCHAR(50), 
	PICKUPDATE VARCHAR(50),
	PICKUPTIME VARCHAR(30), 
	DROPOFFDATE VARCHAR(50),
	DROPOFFTIME VARCHAR(30), 
	SERVICECOST DECIMAL(10,2), 
	BOOKINGDATE VARCHAR(50), 
	PARSTATUS VARCHAR(20)
);
	