CREATE TABLE Users (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 10000, INCREMENT BY 1),
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    mobile VARCHAR(15),
    address VARCHAR(255) NOT NULL,
    password VARCHAR(100) NOT NULL,
    preference VARCHAR(50),
    access VARCHAR(10) DEFAULT 'Customer' NOT NULL
);